# Site settings
title: franzbecker.io
header-img: img/home-bg.jpg
copyright_name: Franz Becker
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.franzbecker.io"
twitter_username: franzbecker_io
github_username: franzbecker

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
